FROM ubuntu:18.04

ENV PATH=$PATH:/opt/jdk-16.0.2/bin

RUN apt update -y \
    && apt-get install -y curl fakeroot binutils \
    && curl https://download.java.net/java/GA/jdk16.0.2/d4a915d82b4c4fbb9bde534da945d746/7/GPL/openjdk-16.0.2_linux-x64_bin.tar.gz > openjdk.tgz \
    && tar -zxvf openjdk.tgz -C /opt